"""Update notifications match_id

Revision ID: 3df68654e952
Revises: 4cba4d66e283
Create Date: 2026-09-04 02:09:38.102343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df68654e952'
down_revision: Union[str, Sequence[str], None] = '4cba4d66e283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'match_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'donor_matches', ['match_id'], ['match_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'donor_matches', ['match_id'], ['id'])
    op.alter_column('notifications', 'match_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
