"""Location system overhaul

Revision ID: 4cba4d66e283
Revises: 001_initial_schema
Create Date: 2026-08-30 13:01:30.335703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cba4d66e283'
down_revision: Union[str, Sequence[str], None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergency_requests', sa.Column('location_name', sa.String(length=255), nullable=True))
    op.add_column('emergency_requests', sa.Column('location_address', sa.String(length=255), nullable=True))
    op.add_column('emergency_requests', sa.Column('location_source', sa.String(length=50), nullable=True))
    op.drop_column('emergency_requests', 'hospital_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergency_requests', sa.Column('hospital_name', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('emergency_requests', 'location_source')
    op.drop_column('emergency_requests', 'location_address')
    op.drop_column('emergency_requests', 'location_name')
    # ### end Alembic commands ###
